"""Generates a LitServe + vLLM server script for a given HuggingFace model.

The returned string is written to a NamedTemporaryFile by the orchestrator
before being submitted to the Lightning AI SDK. The script serves an
OpenAI-compatible ``/v1/chat/completions`` endpoint (compatible with the
existing inference proxy).
"""
from __future__ import annotations

_SCRIPT_TEMPLATE = '''\
# Auto-generated by LLMOps Platform — do not edit
import os
import litserve as ls
from vllm import LLM, SamplingParams

HF_MODEL_ID = os.environ.get("HF_MODEL_ID", "{hf_model_id}")


class VLLMInferenceAPI(ls.LitAPI):
    def setup(self, device):
        self.llm = LLM(model=HF_MODEL_ID)

    def decode_request(self, request):
        messages = request.get("messages", [])
        return "\\n".join(
            f"{m.get(\\'role\\', \\'user\\')}: {m.get(\\'content\\', \\'\\')}" for m in messages
        )

    def predict(self, prompt):
        params = SamplingParams(temperature=0.7, max_tokens=512)
        outputs = self.llm.generate([prompt], params)
        return outputs[0].outputs[0].text

    def encode_response(self, output):
        return {{
            "choices": [
                {{
                    "message": {{"role": "assistant", "content": output}},
                    "finish_reason": "stop",
                    "index": 0,
                }}
            ]
        }}


if __name__ == "__main__":
    server = ls.LitServer(VLLMInferenceAPI(), accelerator="gpu", max_batch_size=1)
    server.run(port=8000)
'''


def generate(hf_model_id: str) -> str:
    """Return a LitServe + vLLM server script string for *hf_model_id*."""
    return _SCRIPT_TEMPLATE.format(hf_model_id=hf_model_id)


__all__ = ["generate"]
